version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=C0nM3May!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - mynetwork

  bookservice:
    build: ./BookService
    container_name: bookservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=Book;User Id=sa;Password=C0nM3May!;TrustServerCertificate=True;
      - Grpc__InventoryGrpc=http://inventoryservice:8080
    depends_on:
      - db
      - inventoryservice
    ports:
      - "5000:8080"
    networks:
      - mynetwork

  inventoryservice:
    build: ./InventoryService
    container_name: inventoryservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=Inventory;User Id=sa;Password=C0nM3May!;TrustServerCertificate=True;
    depends_on:
      - db
    ports:
      - "5001:8080"
    networks:
      - mynetwork

  orderservice:
    build: ./OrderService
    container_name: orderservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=Order;User Id=sa;Password=C0nM3May!;TrustServerCertificate=True;
      - Grpc__BookGrpc=http://bookservice:5000
      - Grpc__InventoryGrpc=http://inventoryservice:5001
    depends_on:
      - db
      - bookservice
      - inventoryservice
    ports:
      - "6001:6000"
    networks:
      - mynetwork

  userservice:
    build: ./UserService
    container_name: userservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=User;User Id=sa;Password=C0nM3May!;TrustServerCertificate=True;
      - Grpc__OrderGrpc=http://orderservice:6000
    depends_on:
      - db
      - orderservice
    ports:
      - "5002:8080"
    networks:
      - mynetwork

  authservice:
    build: ./AuthService
    container_name: authservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Grpc__UserGrpc=http://userservice:5002
    depends_on:
      - userservice
    ports:
      - "5003:8080"
    networks:
      - mynetwork

  apigateway:
    build: ./ApiGateway
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:8080"
    networks:
      - mynetwork
volumes:
  sqlserver_data:

networks:
  mynetwork:
    driver: bridge
